on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  build-deploy:
    name: Build and deploy to GKE Cluster
    runs-on: ubuntu-latest
    env:
      IMAGE: prince2006/shortlet-task:latest
      GKE_CLUSTER: shortlet-cluster
      GKE_ZONE: us-central1
    steps:
      - name: Chackout
        uses: actions/checkout@v3

      - name: Authenticate Google CLI
        id: auth-google-cli
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Authenticate for Docker Hub
        run: docker login -u ${{secrets.D_USER}} -p ${{secrets.D_PASS}}

      - name: Build Image
        run: docker build -t ${{env.IMAGE}}:latest -t ${{env.IMAGE}}:${{github.sha}} .

      - name: Publish Images to DockerHub repo
        run: |
          docker push ${{env.IMAGE}}:latest
          docker push ${{env.IMAGE}}:${{github.sha}}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      - name: Initialize Terraform
        run: |
          cd terraform 
          terraform init

      - name: Check if the GKE Cluster exists
        id: check_cluster
        run: |
          gcloud container clusters describe ${{env.GKE_CLUSTER}} --region us-central1 || echo "Cluster does not exist"

      - name: Apply the Terraform configuration - Set up the GKE Cluster, If the Cluster does NOT exist
        if: steps.check_cluster.outputs.exists == ''
        run: |
          cd terraform 
          terraform apply --auto-approve

      - name: Configure up the GKE Cluster credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Deploy app to Cluster as a deployment
        run: |
          cd kubernetes
          kubectl apply -f kube.yml
          kubectl get pods
